#!/usr/bin/env python3
"""Emit the tor build fragments from src/tor/tor_sources.txt.

makefile.unix and innova-qt.pro both consume generated fragments so the two
build systems cannot drift apart. Run with --check in CI to verify the
fragments match the manifest.
"""

import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "src", "tor", "tor_sources.txt")
MK = os.path.join(ROOT, "src", "tor", "tor_sources.mk")
PRI = os.path.join(ROOT, "src", "tor", "tor_sources.pri")

BANNER = "# Generated by contrib/gen_tor_sources.py from tor_sources.txt. Do not edit.\n"


def read_manifest():
    with open(MANIFEST) as fh:
        srcs = [ln.strip() for ln in fh if ln.strip() and not ln.startswith("#")]
    missing = [s for s in srcs if not os.path.isfile(os.path.join(ROOT, "src", "tor", s))]
    if missing:
        sys.stderr.write("manifest lists %d missing file(s):\n" % len(missing))
        for m in missing:
            sys.stderr.write("  src/tor/%s\n" % m)
        sys.exit(1)
    if len(set(srcs)) != len(srcs):
        sys.stderr.write("manifest contains duplicate entries\n")
        sys.exit(1)
    return srcs


def gen_mk(srcs):
    out = [BANNER, "TOR_OBJS= \\\n"]
    objs = ["\tobj/tor/%s.o" % s[:-2] for s in srcs]
    objs.append("\tobj/tor/anonymize.o")
    out.append(" \\\n".join(objs) + "\n")
    return "".join(out)


def gen_pri(srcs):
    out = [BANNER, "SOURCES += \\\n"]
    paths = ["\tsrc/tor/%s" % s for s in srcs]
    paths.append("\tsrc/tor/anonymize.cpp")
    out.append(" \\\n".join(paths) + "\n")
    return "".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify the fragments are current instead of writing them")
    args = ap.parse_args()

    srcs = read_manifest()
    want = {MK: gen_mk(srcs), PRI: gen_pri(srcs)}

    if args.check:
        bad = False
        for path, text in want.items():
            try:
                with open(path) as fh:
                    have = fh.read()
            except IOError:
                have = None
            if have != text:
                sys.stderr.write("stale or missing: %s\n" % os.path.relpath(path, ROOT))
                bad = True
        if bad:
            sys.stderr.write("run contrib/gen_tor_sources.py to regenerate\n")
            return 1
        print("tor build fragments match tor_sources.txt (%d sources)" % len(srcs))
        return 0

    for path, text in want.items():
        with open(path, "w") as fh:
            fh.write(text)
        print("wrote %s" % os.path.relpath(path, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
