#!/usr/bin/env python3
"""Write the rotating INN coin frames for the startup and build spinners.

usage: generate_innova_coin.py [logo.png]
"""
import math
import os
import subprocess
import sys
import tempfile

from PIL import Image

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT_HEADER = os.path.join(ROOT, "src/innova_spinner_frames.h")
OUT_FRAMES = os.path.join(ROOT, "contrib/innova_coin_frames.txt")
FRAMES = 60
COLS, ROWS = 96, 48          # a terminal cell is about twice as tall as wide
HALF_THICK = 0.14            # coin half-thickness, radius 1
REEDS = 90                   # ridges around the rim
RAMP = " .,:;-=+*#%@"
LIGHT = (-0.45, 0.55, 0.70)


def load_logo(path):
    if path is None:
        tmp = tempfile.mkdtemp()
        subprocess.run(["iconutil", "-c", "iconset", os.path.join(ROOT, "src/qt/res/icons/innova.icns"),
                        "-o", os.path.join(tmp, "i.iconset")], check=True)
        path = os.path.join(tmp, "i.iconset", "icon_512x512.png")
    im = Image.open(path).convert("RGBA")
    bbox = im.getchannel("A").getbbox()
    # The icns circle is slightly squashed; square it before use.
    return im.crop(bbox).resize((256, 256), Image.LANCZOS).getchannel("A")


def norm(v):
    n = math.sqrt(sum(c * c for c in v))
    return tuple(c / n for c in v)


def render(logo, theta):
    px = logo.load()
    lx, ly, lz = norm(LIGHT)
    c, s = math.cos(theta), math.sin(theta)
    rows = []
    for j in range(ROWS):
        y = 1.12 - 2.24 * (j + 0.5) / ROWS
        row = []
        for i in range(COLS):
            x = -1.12 + 2.24 * (i + 0.5) / COLS
            # Orthographic ray toward -z in view space; rotate into coin space (axis z).
            ox, oz = c * x, s * x          # ray origin on the plane z_view = 0
            dx, dz = s, -c                 # view direction (0,0,-1) rotated by -theta
            best = None
            # faces z = +/-HALF_THICK
            if abs(dz) > 1e-6:
                for face in (HALF_THICK, -HALF_THICK):
                    t = (face - oz) / dz
                    hx = ox + t * dx
                    if hx * hx + y * y <= 1.0 and (best is None or t < best[0]):
                        best = (t, "face", face, hx)
            # side of the cylinder: x^2 + y^2 = 1, |z| <= HALF_THICK
            a = dx * dx
            if a > 1e-9:
                disc = (2 * ox * dx) ** 2 - 4 * a * (ox * ox + y * y - 1)
                if disc >= 0:
                    for t in ((-2 * ox * dx - math.sqrt(disc)) / (2 * a), (-2 * ox * dx + math.sqrt(disc)) / (2 * a)):
                        hz = oz + t * dz
                        if abs(hz) <= HALF_THICK and (best is None or t < best[0]):
                            best = (t, "side", hz, ox + t * dx)
            if best is None:
                row.append(" ")
                continue
            _, kind, zz, hx = best
            if kind == "face":
                nx, ny, nz = 0.0, 0.0, 1.0 if zz > 0 else -1.0
                u = hx if zz > 0 else -hx
                tx = min(255, max(0, int((u + 1) * 127.5)))
                ty = min(255, max(0, int((1 - y) * 127.5)))
                inside = px[tx, ty] > 128
                r = math.sqrt(hx * hx + y * y)
                albedo = (1.0 - 0.35 * r * r) if inside else 0.30   # domed field, recessed letters
                if r > 0.92:
                    albedo = 1.0                            # polished outer lip
                elif r > 0.88:
                    albedo = 0.45                           # groove inside the lip
            else:
                ang = math.atan2(y, hx)
                nx, ny, nz = math.cos(ang), math.sin(ang), 0.0
                albedo = 0.55 + 0.45 * (0.5 + 0.5 * math.cos(ang * REEDS))
            # rotate the normal back into view space
            vx = c * nx + s * nz
            vz = -s * nx + c * nz
            lambert = max(0.0, vx * lx + ny * ly + vz * lz)
            # Blinn-Phong highlight toward a viewer on +z, for a metallic face and rim.
            hx_, hy_, hz_ = norm((lx, ly, lz + 1.0))
            spec = max(0.0, vx * hx_ + ny * hy_ + vz * hz_) ** 24
            v = min(1.0, 0.10 + 0.70 * lambert * albedo + 0.35 * spec * albedo)
            row.append(RAMP[min(len(RAMP) - 1, int(v * (len(RAMP) - 1) + 0.5))])
        rows.append("".join(row).rstrip())
    width = COLS
    return [r.ljust(width) for r in rows]


def main():
    logo = load_logo(sys.argv[1] if len(sys.argv) > 1 else None)
    frames = [render(logo, 2 * math.pi * k / FRAMES) for k in range(FRAMES)]
    with open(OUT_HEADER, "w") as h:
        h.write("// Auto-generated by contrib/generate_innova_coin.py\n")
        h.write("#ifndef INNOVA_SPINNER_FRAMES_H\n#define INNOVA_SPINNER_FRAMES_H\n\n")
        h.write("static const int INNOVA_SPINNER_FRAME_COUNT = %d;\n" % FRAMES)
        h.write("static const int INNOVA_SPINNER_LINE_COUNT = %d;\n\n" % ROWS)
        h.write("static const char* INNOVA_SPINNER_FRAMES[INNOVA_SPINNER_FRAME_COUNT][INNOVA_SPINNER_LINE_COUNT] = {\n")
        for f in frames:
            h.write("    {\n")
            for line in f:
                h.write('        "%s",\n' % line.replace("\\", "\\\\").replace('"', '\\"'))
            h.write("    },\n")
        h.write("};\n\n#endif // INNOVA_SPINNER_FRAMES_H\n")
    with open(OUT_FRAMES, "w") as t:
        t.write("\f\n".join("\n".join(f) + "\n" for f in frames))
    print("wrote %d frames of %dx%d" % (FRAMES, COLS, ROWS))


if __name__ == "__main__":
    main()
