version: 2.1
executors:
  cpp-build:
    docker:
      - image: cimg/base:2024.01
    environment:
      MAKEFLAGS: "-j 4"
jobs:
  build:
    executor: cpp-build
    resource_class: large
    steps:
      - run:
          name: 'Checkout via HTTPS'
          command: |
            git clone --filter=blob:none https://github.com/innova-foundation/innova.git .
            if [ -n "$CIRCLE_BRANCH" ]; then
              git checkout "$CIRCLE_BRANCH"
            fi
      - run:
          name: 'Install Dependencies'
          command: |
            sudo apt-get update -y
            sudo apt-get install -y git unzip build-essential libdb++-dev libboost-all-dev \
              libqrencode-dev libminiupnpc-dev libevent-dev autogen automake libtool \
              libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools \
              qtbase5-dev qtbase5-dev-tools libcurl4-openssl-dev libssl-dev \
              ufw make libminizip-dev
      - run:
          name: 'innovad Build'
          command: |
            cd src
            make -f makefile.unix -j4
      - run:
          name: 'Innova QT Build'
          command: |
            sed -i 's/LIBS += -lcurl -lssl -lcrypto -lcrypt32 -lssh2 -lgcrypt -lidn2 -lgpg-error -lunistring -lwldap32 -ldb_cxx$$BDB_LIB_SUFFIX/LIBS += -lcurl -lssl -lcrypto -ldb_cxx$$BDB_LIB_SUFFIX/' innova-qt.pro
            qmake "USE_UPNP=1" "USE_QRCODE=1" "USE_NATIVETOR=1" innova-qt.pro
            make -j4
workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - secp256k1
                - dev
