name: Monero Tests

on:
  push:
    branches:
      - main
      - 'fcmp\+\+'
    paths:
      - "crypto/**"
      - "monero-oxide/**"

  pull_request:
    paths:
      - "crypto/**"
      - "monero-oxide/**"

  workflow_dispatch:

jobs:
  # Only run these once since they will be consistent regardless of any node
  unit-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-26-intel, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0

      - name: Test Dependencies
        uses: ./.github/actions/test-dependencies

      - name: Run Unit Tests With and Without `--all-features`
        shell: bash
        run: |
          # Remove `monero-oxide-verify-chain` which isn't a lib and can't be tested as a lib
          find . -mindepth 2 -type f -name "Cargo.toml" | grep -v "verify-chain" | while IFS="\n" read -r toml; do
            GITHUB_CI=true RUST_BACKTRACE=1 cargo test --manifest-path $toml --lib
            GITHUB_CI=true RUST_BACKTRACE=1 cargo test --manifest-path $toml --lib --all-features
          done

  integration-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-26-intel, macos-latest, windows-latest]
        # Test against all supported protocol versions
        version: [v0.17.3.2, v0.18.4.4]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # 6.0.0

      - name: Test Dependencies
        uses: ./.github/actions/test-dependencies
        with:
          monero-version: ${{ matrix.version }}

      - name: Run Integration Tests
        shell: bash
        run: |
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-oxide --test '*'
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-simple-request-rpc --test '*'
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-wallet --test '*'

      - name: Run Integration Tests With All Features
        shell: bash
        run: |
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-oxide --all-features --test '*'
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-simple-request-rpc --all-features --test '*'
          GITHUB_CI=true RUST_BACKTRACE=1 cargo test --package monero-wallet --all-features --test '*'
