# Copyright (c) 2009-2010 Satoshi Nakamoto
# Copyright (c) 2017-2021 D e n a r i u s [D]
# Copyright (c) 2019-2026 I n n o v a [INN]
# Distributed under the MIT/X11 software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

USE_LEVELDB:=1
USE_UPNP:=1
USE_NATIVETOR:=1
USE_IPFS:=1
UNAME_S := $(shell uname -s)
HOMEBREW_PREFIX := $(shell brew --prefix 2>/dev/null)
# brew --prefix answers with a path whether or not the formula is installed, so
# select on the header being present instead. 5 is tried first: that is what the
# Linux build links against.
BDB_BREW_PREFIX := $(shell for f in berkeley-db@5 berkeley-db@4 berkeley-db; do \
    p=$$(brew --prefix $$f 2>/dev/null); \
    if [ -f "$$p/include/db_cxx.h" ]; then echo "$$p"; break; fi; \
  done)

LINK:=$(CXX)
UNAME_M := $(shell uname -m)
ARCH:=$(shell lscpu 2>/dev/null | head -n 1 | awk '{print $$2}')

DEFS=-DBOOST_SPIRIT_THREADSAFE

DEFS += $(addprefix -I,$(CURDIR) $(CURDIR)/obj $(CURDIR)/json $(BOOST_INCLUDE_PATH) $(BDB_INCLUDE_PATH) $(OPENSSL_INCLUDE_PATH))
OPENSSL_PKGCONF := $(shell pkg-config --cflags openssl 2>/dev/null)
ifneq ($(OPENSSL_PKGCONF),)
    DEFS += $(OPENSSL_PKGCONF)
endif
LIBEVENT_PKGCONF := $(shell pkg-config --cflags libevent 2>/dev/null)
ifneq ($(LIBEVENT_PKGCONF),)
    DEFS += $(LIBEVENT_PKGCONF)
endif
LIBS = $(addprefix -L,$(BOOST_LIB_PATH) $(BDB_LIB_PATH) $(OPENSSL_LIB_PATH))

DEFS += -DIS_ARCH_64

ifneq ($(HOMEBREW_PREFIX),)
    DEFS += -I$(HOMEBREW_PREFIX)/include
    LIBS += -L$(HOMEBREW_PREFIX)/lib
endif
ifneq ($(BDB_BREW_PREFIX),)
    DEFS += -I$(BDB_BREW_PREFIX)/include
    LIBS += -L$(BDB_BREW_PREFIX)/lib
endif

OPENSSL_VERSION := $(shell pkg-config --modversion openssl 2>/dev/null)
ifneq ($(OPENSSL_VERSION),)
ifeq ($(origin USE_NATIVETOR), file)
ifneq ($(filter 3.%,$(OPENSSL_VERSION)),)
    USE_NATIVETOR := -
endif
endif
endif

LMODE = dynamic
LMODE2 = dynamic
ifdef STATIC
    LMODE = static
    ifeq (${STATIC}, all)
        LMODE2 = static
    endif
endif

ifeq ($(UNAME_S),Darwin)
    LDLIBMODE =
    LDLIBMODE2 =
    DL_LIB =
    DARWIN_LDFLAGS = -Wl,-no_fixup_chains -Wl,-adhoc_codesign
    DARWIN_FRAMEWORKS = -framework CoreFoundation -framework IOKit
else
    LDLIBMODE = -Wl,-B$(LMODE)
    LDLIBMODE2 = -Wl,-B$(LMODE2)
    DL_LIB = -l dl
endif

# for boost 1.37, add -mt to the boost libraries
LIBS += \
 $(LDLIBMODE) \
   -l boost_filesystem$(BOOST_LIB_SUFFIX) \
   -l boost_program_options$(BOOST_LIB_SUFFIX) \
   -l boost_thread$(BOOST_LIB_SUFFIX) \
   -l boost_chrono$(BOOST_LIB_SUFFIX) \
   -l db_cxx$(BDB_LIB_SUFFIX) \
   -l curl \
   -l ssl \
   -l crypto \
   -l event

ifndef USE_NATIVETOR
  override USE_NATIVETOR = -
endif
ifneq (${USE_NATIVETOR}, -)
  DEFS += $(addprefix -I,$(CURDIR)/tor) -DUSE_NATIVETOR=$(USE_NATIVETOR)
endif

ifndef USE_IPFS
  override USE_IPFS = -
endif
ifneq (${USE_IPFS}, -)
  DEFS += $(addprefix -I,$(CURDIR)/ipfs) -DUSE_IPFS=$(USE_IPFS)
endif

ifndef USE_UPNP
    override USE_UPNP = -
endif
ifneq (${USE_UPNP}, -)
    LIBS += -l miniupnpc
    DEFS += -DUSE_UPNP=$(USE_UPNP)
endif

LIBS+= \
 $(LDLIBMODE2) \
   -l z \
   $(DL_LIB) \
   -l pthread


# Hardening
# Make some classes of vulnerabilities unexploitable in case one is discovered.
#
    # This is a workaround for Ubuntu bug #691722, the default -fstack-protector causes
    # -fstack-protector-all to be ignored unless -fno-stack-protector is used first.
    # see: https://bugs.launchpad.net/ubuntu/+source/gcc-4.5/+bug/691722
    HARDENING=-fno-stack-protector

    # Stack Canaries
    # Put numbers at the beginning of each stack frame and check that they are the same.
    # If a stack buffer if overflowed, it writes over the canary number and then on return
    # when that number is checked, it won't be the same and the program will exit with
    # a "Stack smashing detected" error instead of being exploited.
    HARDENING+=-fstack-protector-all -Wstack-protector

    # Make some important things such as the global offset table read only as soon as
    # the dynamic linker is finished building it. This will prevent overwriting of addresses
    # which would later be jumped to.
    ifneq ($(UNAME_S),Darwin)
        LDHARDENING+=-Wl,-z,relro -Wl,-z,now
    endif

    # Build position independent code to take advantage of Address Space Layout Randomization
    # offered by some kernels.
    # see doc/build-unix.txt for more information.
    ifdef PIE
        HARDENING+=-fPIE
        LDHARDENING+=-pie
    endif

    # -D_FORTIFY_SOURCE=2 does some checking for potentially exploitable code patterns in
    # the source such overflowing a statically defined buffer.
    HARDENING+=-D_FORTIFY_SOURCE=2
#


DEBUGFLAGS=-g


ifeq (${ARCH}, i686)
    EXT_OPTIONS=-msse2
endif


# CXXFLAGS can be specified on the make command line, so we use xCXXFLAGS that only
# adds some defaults in front. Unfortunately, CXXFLAGS=... $(CXXFLAGS) does not work.
xCXXFLAGS=-O2 $(EXT_OPTIONS) -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wno-format -Wno-unused-parameter -Wno-literal-suffix -Wno-deprecated-declarations -Wno-deprecated-copy -std=c++17 \
    $(DEBUGFLAGS) $(DEFS) $(HARDENING) $(CXXFLAGS)

xCFLAGS=-O2 $(EXT_OPTIONS) -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wno-format -Wno-unused-parameter -Wno-deprecated-declarations \
    $(DEBUGFLAGS) $(DEFS) $(HARDENING) $(CFLAGS)

# LDFLAGS can be specified on the make command line, so we use xLDFLAGS that only
# adds some defaults in front. Unfortunately, LDFLAGS=... $(LDFLAGS) does not work.
xLDFLAGS=$(LDHARDENING) $(DARWIN_LDFLAGS) $(LDFLAGS)

ifdef SANITIZE
    xCXXFLAGS += -fsanitize=$(SANITIZE) -fno-omit-frame-pointer
    xCFLAGS += -fsanitize=$(SANITIZE) -fno-omit-frame-pointer
    xLDFLAGS += -fsanitize=$(SANITIZE)
endif

ifeq (${USE_NATIVETOR}, 1)
OBJS= \
	obj/address.o \
	obj/addressmap.o \
	obj/aes.o \
	obj/anonymize.o \
	obj/backtrace.o \
	obj/blinding.o \
	obj/bridges.o \
	obj/buffers.o \
	obj/cell_common.o \
	obj/cell_establish_intro.o \
	obj/cell_introduce1.o \
	obj/channel.o \
	obj/channeltls.o \
	obj/circpathbias.o \
	obj/circuitbuild.o \
	obj/circuitlist.o \
	obj/circuitmux.o \
	obj/circuitmux_ewma.o \
	obj/circuitstats.o \
	obj/circuituse.o \
	obj/command.o \
	obj/compat_libevent.o \
	obj/compat_pthreads.o \
	obj/compat_threads.o \
	obj/compat_time.o \
	obj/config.o \
	obj/confparse.o \
	obj/connection.o \
	obj/connection_edge.o \
	obj/connection_or.o \
	obj/container.o \
	obj/control.o \
	obj/crypto.o \
	obj/crypto_curve25519.o \
	obj/crypto_ed25519.o \
	obj/crypto_format.o \
	obj/crypto_pwbox.o \
	obj/crypto_s2k.o \
	obj/cpuworker.o \
	obj/csiphash.o \
	obj/curve25519-donna.o \
	obj/di_ops.o \
	obj/dircollate.o \
	obj/directory.o \
	obj/dirserv.o \
	obj/dirvote.o \
	obj/dns.o \
	obj/dnsserv.o \
	obj/ed25519_cert.o \
	obj/ed25519_tor.o \
	obj/entrynodes.o \
	obj/ext_orport.o \
	obj/fe_copy.o \
	obj/fe_cmov.o \
	obj/fe_isnegative.o \
	obj/fe_sq.o \
	obj/fe_pow22523.o \
	obj/fe_isnonzero.o \
	obj/fe_neg.o \
	obj/fe_frombytes.o \
	obj/fe_invert.o \
	obj/fe_sub.o \
	obj/fe_add.o \
	obj/fe_1.o \
	obj/fe_mul.o \
	obj/fe_tobytes.o \
	obj/fe_0.o \
	obj/fe_sq2.o \
	obj/fp_pair.o \
	obj/ge_scalarmult_base.o \
	obj/ge_p3_tobytes.o \
	obj/ge_frombytes.o \
	obj/ge_double_scalarmult.o \
	obj/ge_tobytes.o \
	obj/ge_p3_to_cached.o \
	obj/ge_p3_to_p2.o \
	obj/ge_p3_dbl.o \
	obj/ge_p3_0.o \
	obj/ge_p1p1_to_p2.o \
	obj/ge_p1p1_to_p3.o \
	obj/ge_add.o \
	obj/ge_p2_0.o \
	obj/ge_p2_dbl.o \
	obj/ge_madd.o \
	obj/ge_msub.o \
	obj/ge_sub.o \
	obj/ge_precomp_0.o \
	obj/geoip.o \
	obj/hibernate.o \
	obj/hs_cache.o \
	obj/hs_circuitmap.o \
	obj/hs_common.o \
	obj/hs_descriptor.o \
	obj/hs_intropoint.o \
	obj/hs_service.o \
	obj/keyconv.o \
	obj/keypair.o \
	obj/keypin.o \
	obj/keccak-tiny-unrolled.o \
	obj/link_handshake.o \
	obj/log.o \
	obj/tormain.o \
	obj/memarea.o \
	obj/microdesc.o \
	obj/networkstatus.o \
	obj/nodelist.o \
	obj/ntmain.o \
	obj/onion.o \
	obj/onion_fast.o \
	obj/onion_ntor.o \
	obj/onion_tap.o \
	obj/open.o \
	obj/parsecommon.o \
	obj/periodic.o \
	obj/policies.o \
	obj/procmon.o \
	obj/protover.o \
	obj/pwbox.o \
	obj/reasons.o \
	obj/readpassphrase.o \
	obj/relay.o \
	obj/rendcache.o \
	obj/rendclient.o \
	obj/rendcommon.o \
	obj/rendmid.o \
	obj/rendservice.o \
	obj/rephist.o \
	obj/replaycache.o \
	obj/router.o \
	obj/routerkeys.o \
	obj/routerlist.o \
	obj/routerparse.o \
	obj/routerset.o \
	obj/sandbox.o \
	obj/sc_reduce.o \
	obj/sc_muladd.o \
	obj/scheduler.o \
	obj/shared_random.o \
	obj/shared_random_state.o \
	obj/sign.o \
	obj/statefile.o \
	obj/status.o \
	obj/torcert.o \
	obj/torcompat.o \
	obj/tor_main.o \
	obj/torgzip.o \
	obj/tortls.o \
	obj/torutil.o \
	obj/transports.o \
	obj/trunnel.o \
	obj/util_bug.o \
	obj/util_format.o \
	obj/util_process.o \
	obj/workqueue.o \
    obj/echo.o \
    obj/jh.o \
    obj/keccak.o \
    obj/alert.o \
    obj/version.o \
    obj/checkpoints.o \
    obj/netbase.o \
    obj/addrman.o \
    obj/crypter.o \
    obj/key.o \
    obj/hash.o \
    obj/base58.o \
    obj/db.o \
    obj/init.o \
    obj/keystore.o \
    obj/miner.o \
    obj/main.o \
    obj/net.o \
    obj/core.o \
    obj/protocol.o \
    obj/innovarpc.o \
    obj/rpcdump.o \
    obj/rpcnet.o \
    obj/rpcmining.o \
    obj/rpcwallet.o \
    obj/rpcblockchain.o \
    obj/pod.o \
    obj/rpcrawtransaction.o \
	obj/rpchyperfile.o \
    obj/rpcshielded.o \
    obj/nullsend.o \
    obj/shielded.o \
    obj/privacy_vnext_ffi.o \
    obj/privacy_vnext_store.o \
    obj/privacy_vnext_builder.o \
    obj/zkproof.o \
    obj/verifycache.o \
    obj/lelantus.o \
    obj/curvetree.o \
    obj/ipa.o \
    obj/ed25519_zk.o \
    obj/nullstake.o \
    obj/poseidon2.o \
    obj/bulletproof_ac.o \
    obj/silentpayments.o \
    obj/dandelion.o \
    obj/finality.o \
    obj/finality_note.o \
    obj/finality_schedule.o \
    obj/dag.o \
    obj/blockprofile.o \
    obj/rpcsmessage.o \
    obj/rpcnyx.o \
    obj/script.o \
    obj/sync.o \
    obj/util.o \
    obj/wallet.o \
    obj/walletdb.o \
    obj/noui.o \
    obj/kernel.o \
    obj/pbkdf2.o \
    obj/scrypt.o \
    obj/smessage.o \
    obj/stealth.o \
    obj/activecollateralnode.o \
    obj/collateralnodeconfig.o \
    obj/collateralnode.o \
    obj/rpccollateral.o \
    obj/spork.o \
    obj/collateral.o \
    obj/eccryptoverify.o \
    obj/ringsig.o \
    obj/bloom.o \
    obj/state.o \
	obj/idns.o \
	obj/namecoin.o \
	obj/utiltime.o \
    obj/stun.o \
    obj/bootstrap.o \
    obj/minizip/ioapi.o \
    obj/minizip/unzip.o
else
OBJS= \
    obj/echo.o \
    obj/jh.o \
    obj/keccak.o \
    obj/alert.o \
    obj/version.o \
    obj/checkpoints.o \
    obj/netbase.o \
    obj/addrman.o \
    obj/crypter.o \
    obj/key.o \
    obj/hash.o \
    obj/base58.o \
    obj/db.o \
    obj/init.o \
    obj/keystore.o \
    obj/miner.o \
    obj/main.o \
    obj/net.o \
    obj/core.o \
    obj/protocol.o \
    obj/innovarpc.o \
    obj/rpcdump.o \
    obj/rpcnet.o \
    obj/rpcmining.o \
    obj/rpcwallet.o \
    obj/rpcblockchain.o \
    obj/pod.o \
    obj/rpcrawtransaction.o \
    obj/rpcsmessage.o \
    obj/rpcnyx.o \
	obj/rpchyperfile.o \
    obj/rpcshielded.o \
    obj/nullsend.o \
    obj/shielded.o \
    obj/privacy_vnext_ffi.o \
    obj/privacy_vnext_store.o \
    obj/privacy_vnext_builder.o \
    obj/zkproof.o \
    obj/verifycache.o \
    obj/lelantus.o \
    obj/curvetree.o \
    obj/ipa.o \
    obj/ed25519_zk.o \
    obj/nullstake.o \
    obj/poseidon2.o \
    obj/bulletproof_ac.o \
    obj/silentpayments.o \
    obj/dandelion.o \
    obj/finality.o \
    obj/finality_note.o \
    obj/finality_schedule.o \
    obj/dag.o \
    obj/blockprofile.o \
    obj/script.o \
    obj/sync.o \
    obj/util.o \
    obj/wallet.o \
    obj/walletdb.o \
    obj/noui.o \
    obj/kernel.o \
    obj/pbkdf2.o \
    obj/scrypt.o \
    obj/smessage.o \
    obj/stealth.o \
    obj/activecollateralnode.o \
    obj/collateralnodeconfig.o \
    obj/collateralnode.o \
    obj/rpccollateral.o \
    obj/spork.o \
    obj/collateral.o \
    obj/eccryptoverify.o \
    obj/ringsig.o \
    obj/bloom.o \
    obj/state.o \
	obj/idns.o \
	obj/namecoin.o \
	obj/utiltime.o \
    obj/stun.o \
    obj/bootstrap.o \
    obj/minizip/ioapi.o \
    obj/minizip/unzip.o
endif

# IPFS objects
ifeq (${USE_IPFS}, 1)
OBJS += obj/ipfs.o obj/ipfscurl.o
endif

# Scrypt assembly - architecture-conditional
ifeq ($(UNAME_M),x86_64)
OBJS += obj/scrypt-x86_64.o
else ifeq ($(UNAME_M),i686)
OBJS += obj/scrypt-x86.o
else ifneq (,$(filter arm% aarch64,$(UNAME_M)))
OBJS += obj/scrypt-arm.o
endif

TEST_OBJS= \
    obj/test/test_innova.o \
    obj/test/allocator_tests.o \
    obj/test/base32_tests.o \
    obj/test/base64_tests.o \
    obj/test/getarg_tests.o \
    obj/test/mruset_tests.o \
    obj/test/netbase_tests.o \
    obj/test/ringsig_tests.o \
    obj/test/rpc_tests.o \
    obj/test/sigopcount_tests.o \
    obj/test/bulletproof_ac_tests.o \
    obj/test/finality_tally_tests.o \
    obj/test/finality_note_tests.o \
    obj/test/finality_note_carrier_tests.o \
    obj/test/fcmp_root_tests.o \
    obj/test/pod_tests.o \
    obj/test/privacy_vnext_abi_tests.o \
    obj/test/privacy_vnext_store_tests.o \
    obj/test/privacy_vnext_builder_tests.o \
    obj/test/privacy_vnext_collateral_tests.o \
    obj/test/idag_validation_tests.o \
    obj/test/shielded_nullifier_binding_tests.o \
    obj/test/finality_vote_binding_tests.o \
    obj/test/nullsend_binding_tests.o \
    obj/test/coinstake_guard_tests.o \
    obj/test/retarget_tests.o \
    obj/test/emission_curve_tests.o \
    obj/test/finality_coldstart_tests.o \
    obj/test/finality_committee_sig_tests.o \
    obj/test/halfagg_stake_tests.o \
    obj/test/epoch_state_determinism_tests.o \
    obj/test/dagknight_anchor_cache_tests.o \
    obj/test/finality_committee_draw_tests.o \
    obj/test/finality_settlement_tests.o \
    obj/test/finality_vote_schedule_tests.o \
    obj/test/name_index_recovery_tests.o \
    obj/test/name_rental_tests.o \
    obj/test/fuzz_deserialize_tests.o \
    obj/test/smessage_hmac_tests.o \
    obj/test/smessage_bounds_tests.o \
    obj/test/base58_tests.o \
    obj/test/bignum_tests.o \
    obj/test/key_tests.o \
    obj/test/uint160_tests.o \
    obj/test/uint256_tests.o \
    obj/test/util_tests.o \
    obj/test/Checkpoints_tests.o \
    obj/test/DoS_tests.o \
    obj/test/script_P2SH_tests.o \
    obj/test/script_tests.o \
    obj/test/transaction_tests.o \
    obj/test/multisig_tests.o \
    obj/test/wallet_tests.o \
    obj/test/accounting_tests.o \
    obj/test/miner_tests.o

FUZZ_CXX ?= clang++
FUZZ_COMPILE_FLAGS ?= -O1 -g -fsanitize=fuzzer-no-link,address,undefined -fno-omit-frame-pointer
FUZZ_LINK_FLAGS ?= -O1 -g -fsanitize=fuzzer,address,undefined -fno-omit-frame-pointer
FUZZ_DESERIALIZE_BIN ?= fuzz_deserialize
FUZZ_DESERIALIZE_OBJ ?= obj/fuzz/fuzz_deserialize.o

.PHONY: all innova-build audit-test-dependencies fuzz-deserialize fuzz-deserialize-libfuzzer check-legacy-aggregate check-bpac check-finality-tally check-fcmp check-idag-validation check-shielded-nullifier-binding check-finality-vote-binding check-nullsend-binding check-coinstake-guard check-retarget check-finality-committee-sig check-halfagg-stake check-epoch-state-determinism check-dagknight-anchor-cache check-finality-settlement check-finality-note check-privacy-vnext check-name-index-recovery check-name-rental check-fuzz-deserialize-limits check-smessage-hmac check-emission-curve check-finality-coldstart check-finality-vote-schedule check-privacy-vnext-provenance check-privacy-vnext-freshness check-all release-check

INNOVA_SPINNER ?= 1
INNOVA_SPINNER_SCRIPT ?= ../contrib/innova_build_spinner.sh

ifeq ($(INNOVA_SPINNER),1)
all:
	@$(INNOVA_SPINNER_SCRIPT) $(MAKE) -f makefile.unix INNOVA_SPINNER=0 innova-build
else
all: innova-build
endif

innova-build: innovad

audit-test-dependencies:
	../contrib/test/audit_build_dependencies.sh

# The vendored crate set and the pinned ABI are consensus inputs, so a release
# build has to prove them rather than assume them.
check-privacy-vnext-provenance:
	python3 privacy_vnext/rust/tools/verify_provenance.py

# Belt-and-braces against the rule that produces the archive being wrong again: this
# reads mtimes, not the dependency graph, so a bad prerequisite list cannot hide from it.
check-privacy-vnext-freshness:
	PRIVACY_VNEXT_RUST_PROFILE=$(PRIVACY_VNEXT_RUST_PROFILE) \
	    ../contrib/test/check_privacy_vnext_freshness.sh

fuzz-deserialize: $(FUZZ_DESERIALIZE_OBJ)

$(FUZZ_DESERIALIZE_OBJ): test/fuzz/fuzz_deserialize.cpp
	@mkdir -p $(@D)
	$(FUZZ_CXX) $(filter-out -D_FORTIFY_SOURCE=2,$(xCXXFLAGS)) $(FUZZ_COMPILE_FLAGS) -DINNOVA_FUZZ_STANDALONE -MMD -MF $(@:%.o=%.d) -c -o $@ $<

fuzz-deserialize-libfuzzer:
	$(FUZZ_CXX) $(filter-out -D_FORTIFY_SOURCE=2,$(xCXXFLAGS)) $(FUZZ_LINK_FLAGS) -DINNOVA_FUZZ_STANDALONE -o $(FUZZ_DESERIALIZE_BIN) test/fuzz/fuzz_deserialize.cpp

FUZZ_SCRIPT_BIN ?= fuzz_script
FUZZ_BLOCK_HEADER_BIN ?= fuzz_block_header

# fuzz_script.cpp exercises real CScript/Solver behavior, so the implementation
# must be compiled in alongside it, instrumented with the same flags.
FUZZ_SCRIPT_SRCS ?= test/fuzz/fuzz_script.cpp test/fuzz/fuzz_stubs.cpp script.cpp key.cpp hash.cpp util.cpp netbase.cpp sync.cpp keystore.cpp crypter.cpp version.cpp noui.cpp scrypt.cpp pbkdf2.cpp

fuzz-script-libfuzzer:
	$(FUZZ_CXX) $(filter-out -D_FORTIFY_SOURCE=2,$(xCXXFLAGS)) $(FUZZ_LINK_FLAGS) -DINNOVA_FUZZ_STANDALONE -o $(FUZZ_SCRIPT_BIN) $(FUZZ_SCRIPT_SRCS) $(LIBS)

# The header hash is Tribus (jh + keccak + echo). Those are C sources and must be
# compiled as C; feeding them to the C++ driver breaks overload resolution.
FUZZ_CC ?= clang
FUZZ_BLOCK_HEADER_SRCS ?= test/fuzz/fuzz_block_header.cpp test/fuzz/fuzz_stubs.cpp util.cpp netbase.cpp sync.cpp version.cpp noui.cpp
FUZZ_TRIBUS_SRCS ?= jh.c keccak.c echo.c
FUZZ_TRIBUS_OBJS ?= obj/fuzz/jh.o obj/fuzz/keccak.o obj/fuzz/echo.o

obj/fuzz/%.o: %.c
	@mkdir -p $(@D)
	$(FUZZ_CC) $(filter-out -D_FORTIFY_SOURCE=2,$(xCFLAGS)) $(FUZZ_COMPILE_FLAGS) -c -o $@ $<

fuzz-block-header-libfuzzer: $(FUZZ_TRIBUS_OBJS)
	$(FUZZ_CXX) $(filter-out -D_FORTIFY_SOURCE=2,$(xCXXFLAGS)) $(FUZZ_LINK_FLAGS) -DINNOVA_FUZZ_STANDALONE -o $(FUZZ_BLOCK_HEADER_BIN) $(FUZZ_BLOCK_HEADER_SRCS) $(FUZZ_TRIBUS_OBJS) $(LIBS)

fuzz-all-libfuzzer: fuzz-deserialize-libfuzzer fuzz-script-libfuzzer fuzz-block-header-libfuzzer

check-legacy-aggregate: test_innova
	./test_innova --run_test=allocator_tests,base32_tests,base58_tests,base64_tests,bignum_tests,Checkpoints_tests,DoS_tests,getarg_tests,key_tests,mruset_tests,multisig_tests,netbase_tests,ringsig_tests,rpc_tests,script_P2SH_tests,script_tests,sigopcount_tests,transaction_tests,uint160_tests,uint256_tests,util_tests,wallet_tests,accounting_tests,miner_tests

check-bpac: test_innova
	./test_innova --run_test=bulletproof_ac_tests

check-finality-tally: test_innova
	./test_innova --run_test=finality_tally_tests

check-fcmp: test_innova
	./test_innova --run_test=fcmp_root_tests

check-idag-validation: test_innova
	./test_innova --run_test=idag_validation_tests

check-shielded-nullifier-binding: test_innova
	./test_innova --run_test=shielded_nullifier_binding_tests,shielded_nullifier_binding_proof_tests

check-finality-vote-binding: test_innova
	./test_innova --run_test=finality_vote_binding_tests

check-nullsend-binding: test_innova
	./test_innova --run_test=nullsend_binding_tests

check-coinstake-guard: test_innova
	./test_innova --run_test=coinstake_guard_tests

check-retarget: test_innova
	./test_innova --run_test=retarget_tests
check-emission-curve: test_innova
	./test_innova --run_test=emission_curve_tests

check-finality-coldstart: test_innova
	./test_innova --run_test=finality_coldstart_tests

check-finality-committee-sig: test_innova
	./test_innova --run_test=finality_committee_sig_tests

check-finality-committee-draw: test_innova
	./test_innova --run_test=finality_committee_draw_tests

check-halfagg-stake: test_innova
	./test_innova --run_test=halfagg_stake_tests

check-epoch-state-determinism: test_innova
	./test_innova --run_test=epoch_state_determinism_tests

check-dagknight-anchor-cache: test_innova
	./test_innova --run_test=dagknight_anchor_cache_tests

check-finality-settlement: test_innova
	./test_innova --run_test=finality_settlement_tests

check-finality-vote-schedule: test_innova
	./test_innova --run_test=finality_vote_schedule_tests

check-finality-note: test_innova
	./test_innova --run_test=finality_note_tests,finality_note_carrier_tests

check-privacy-vnext: test_innova
	./test_innova --run_test=privacy_vnext_abi_tests,privacy_vnext_builder_tests,privacy_vnext_store_tests,privacy_vnext_collateral_tests

check-name-index-recovery: test_innova
	./test_innova --run_test=name_index_recovery_tests

check-name-rental: test_innova
	./test_innova --run_test=name_rental_tests

check-fuzz-deserialize-limits: test_innova
	./test_innova --run_test=fuzz_deserialize_tests

check-smessage-hmac: test_innova
	./test_innova --run_test=smessage_hmac_tests

check-smessage-bounds: test_innova
	./test_innova --run_test=smessage_bounds_tests

# A suite name is not a file name, so no glob over test/*.cpp can enumerate the
# suites: shielded_nullifier_binding_tests.cpp defines two and test_innova.cpp
# defines none. Running the binary with no --run_test filter takes the executed
# set from the linked binary instead of from a list kept beside it, so a suite
# that is compiled cannot go unrun.
check-all: test_innova
	./test_innova

release-check: audit-test-dependencies innova-build check-all check-legacy-aggregate check-bpac check-finality-tally check-fcmp check-idag-validation check-shielded-nullifier-binding check-finality-vote-binding check-nullsend-binding check-coinstake-guard check-retarget check-finality-committee-sig check-halfagg-stake check-epoch-state-determinism check-dagknight-anchor-cache check-finality-settlement check-finality-note check-privacy-vnext check-name-index-recovery check-name-rental check-fuzz-deserialize-limits check-smessage-hmac check-emission-curve check-finality-coldstart check-finality-vote-schedule check-privacy-vnext-provenance check-privacy-vnext-freshness

#
# LevelDB support
#
ifeq (${USE_LEVELDB}, 1)
LIBS += $(CURDIR)/leveldb/libleveldb.a $(CURDIR)/leveldb/libmemenv.a
DEFS += $(addprefix -I,$(CURDIR)/leveldb/include) -DUSE_LEVELDB
DEFS += $(addprefix -I,$(CURDIR)/leveldb/helpers)
OBJS += obj/txdb-leveldb.o
# FORCE, not a prerequisite list: enumerating LevelDB's sources here would drift the
# same way the IV5 archive's list did. Descend every time and let the nested make,
# which does track its own sources, decide whether anything needs rebuilding.
leveldb/libleveldb.a: FORCE
	@echo "Building LevelDB ..."
	+$(MAKE) -C leveldb CC="$(CC)" CXX="$(CXX)" \
		CFLAGS="$(xCFLAGS)" CXXFLAGS="$(xCXXFLAGS)" LDFLAGS="$(xLDFLAGS)" \
		libleveldb.a libmemenv.a
obj/txdb-leveldb.o: leveldb/libleveldb.a
endif
ifneq (${USE_LEVELDB}, 1)
OBJS += obj/txdb-bdb.o
endif

# auto-generated dependencies:
# Keep nested test/minizip objects header-correct.  Omitting obj/test/*.P can
# silently link ABI-stale tests after a consensus/proof header changes.
-include obj/*.P obj/*/*.P

obj/build.h: FORCE
	/bin/sh ../share/genbuild.sh obj/build.h
version.cpp: obj/build.h
DEFS += -DHAVE_BUILD_INFO

obj/scrypt-x86.o: scrypt-x86.S
	$(CXX) -c $(xCXXFLAGS) -MMD -o $@ $<

obj/scrypt-x86_64.o: scrypt-x86_64.S
	$(CXX) -c $(xCXXFLAGS) -MMD -o $@ $<

obj/scrypt-arm.o: scrypt-arm.S
	$(CXX) -c $(xCXXFLAGS) -MMD -o $@ $<

obj/%.o: %.c
	@mkdir -p $(@D)
	$(CC) -c $(xCFLAGS) -MMD -MF $(@:%.o=%.d) -o $@ $<
	@cp $(@:%.o=%.d) $(@:%.o=%.P); \
	sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
	-e '/^$$/ d' -e 's/$$/ :/' < $(@:%.o=%.d) >> $(@:%.o=%.P); \
	rm -f $(@:%.o=%.d)

obj/minizip/%.o: minizip/%.c
	@mkdir -p obj/minizip
	$(CC) -c $(xCFLAGS) -Wno-incompatible-pointer-types -MMD -MF $(@:%.o=%.d) -o $@ $<
	@cp $(@:%.o=%.d) $(@:%.o=%.P); \
	sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
	-e '/^$$/ d' -e 's/$$/ :/' < $(@:%.o=%.d) >> $(@:%.o=%.P); \
	rm -f $(@:%.o=%.d)

obj/%.o: %.cpp
	@mkdir -p $(@D)
	$(CXX) -c $(xCXXFLAGS) -fpermissive -MMD -MF $(@:%.o=%.d) -o $@ $<
	@cp $(@:%.o=%.d) $(@:%.o=%.P); \
    sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
    -e '/^$$/ d' -e 's/$$/ :/' < $(@:%.o=%.d) >> $(@:%.o=%.P); \
	rm -f $(@:%.o=%.d)

obj/%.o: json/%.cpp
	$(CXX) -c $(xCXXFLAGS) -MMD -MF $(@:%.o=%.d) -o $@ $<
	@cp $(@:%.o=%.d) $(@:%.o=%.P); \
	sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
	-e '/^$$/ d' -e 's/$$/ :/' < $(@:%.o=%.d) >> $(@:%.o=%.P); \
	rm -f $(@:%.o=%.d)

ifeq (${USE_NATIVETOR}, 1)
obj/%.o: tor/%.c
	$(CC) -c $(xCFLAGS) -MMD -MF $(@:%.o=%.d) -o $@ $<
	@cp $(@:%.o=%.d) $(@:%.o=%.P); \
	sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
	-e '/^$$/ d' -e 's/$$/ :/' < $(@:%.o=%.d) >> $(@:%.o=%.P); \
	rm -f $(@:%.o=%.d)

obj/anonymize.o: tor/anonymize.cpp
	$(CXX) -c $(xCXXFLAGS) -MMD -MF $(@:%.o=%.d) -o $@ $<
	@cp $(@:%.o=%.d) $(@:%.o=%.P); \
	sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
	-e '/^$$/ d' -e 's/$$/ :/' < $(@:%.o=%.d) >> $(@:%.o=%.P); \
	rm -f $(@:%.o=%.d)
endif

ifeq (${USE_IPFS}, 1)
obj/%.o: %.cc
	$(CXX) -c $(xCXXFLAGS) -MMD -MF $(@:%.o=%.d) -o $@ $<
	@cp $(@:%.o=%.d) $(@:%.o=%.P); \
	sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
	-e '/^$$/ d' -e 's/$$/ :/' < $(@:%.o=%.d) >> $(@:%.o=%.P); \
	rm -f $(@:%.o=%.d)
endif

PRIVACY_VNEXT_RUST_DIR := $(CURDIR)/privacy_vnext/rust
# The vendored proof library is a dependency, not the code under test, so it is
# built optimized even for debug builds of the daemon: unoptimized, its proof
# math put the unit suite over an hour, which is long enough that a release gate
# gets skipped. Set PRIVACY_VNEXT_RUST_DEBUG=1 to step through the crate itself.
PRIVACY_VNEXT_RUST_PROFILE := release
PRIVACY_VNEXT_RUST_FLAGS := --release
ifdef PRIVACY_VNEXT_RUST_DEBUG
PRIVACY_VNEXT_RUST_PROFILE := debug
PRIVACY_VNEXT_RUST_FLAGS :=
endif
PRIVACY_VNEXT_RUST_LIB := $(PRIVACY_VNEXT_RUST_DIR)/target/$(PRIVACY_VNEXT_RUST_PROFILE)/libinnova_privacy_vnext.a
# Cargo is the freshness authority here: it tracks the crate's own sources and
# the seven path dependencies under upstream/. A hand-written prerequisite list
# covered neither and linked a stale consensus decoder. A no-op build leaves the
# archive's timestamp alone, so this does not force a relink.
$(PRIVACY_VNEXT_RUST_LIB): FORCE
	cd $(PRIVACY_VNEXT_RUST_DIR) && cargo build --locked --offline $(PRIVACY_VNEXT_RUST_FLAGS)

innovad: $(OBJS:obj/%=obj/%) $(PRIVACY_VNEXT_RUST_LIB)
	$(LINK) $(xCXXFLAGS) -o $@ $^ $(xLDFLAGS) $(LIBS) $(DARWIN_FRAMEWORKS)

test_innova: $(filter-out obj/init.o,$(OBJS:obj/%=obj/%)) $(TEST_OBJS) $(PRIVACY_VNEXT_RUST_LIB)
	$(LINK) $(xCXXFLAGS) -o $@ $^ $(xLDFLAGS) $(LIBS) -lboost_unit_test_framework $(DARWIN_FRAMEWORKS)

clean:
	rm -f innovad
	rm -f test_innova
	rm -f $(FUZZ_DESERIALIZE_BIN)
	rm -f obj/*.o
	rm -f obj/*.P
	rm -f obj/*.d
	rm -f obj/test/*.o
	rm -f obj/test/*.P
	rm -f obj/test/*.d
	rm -rf obj/fuzz
	rm -f obj/build.h
	rm -f obj/tor/*.o
	rm -f obj/tor/*.P
	rm -f obj/ipfs/*.o
	rm -f obj/ipfs/*.P
	rm -rf obj/minizip
	+$(MAKE) -C leveldb clean

FORCE:
